# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/QT/application_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_model_page(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_model_page, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Automatic Geomorphological Classification Tool")
        Dialog.setWindowIcon(QIcon("dde.ico"))
        Dialog.resize(2000, 1400)
        Dialog.setWindowFlag(Qt.WindowMinimizeButtonHint)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)

        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 1200, 1400))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")

      # application_label
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 421, 51))
        self.label_2.setStyleSheet("font: 75 20pt \"Agency FB\";\n""color: rgb(188, 188, 188);\n""color: rgb(191, 191, 191);\n""\n""")
        self.label_2.setObjectName("label_2")


       # model_label
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(530, 100, 421, 51))
        self.label_6.setStyleSheet("font: 75 20pt \"Agency FB\";\n""\n""")
        self.label_6.setObjectName("label_6")


       #data_label
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(900, 100, 421, 51))
        self.label_7.setStyleSheet("font: 75 20pt \"Agency FB\";\n""color: rgb(188, 188, 188);\n""color: rgb(191, 191, 191);\n""\n""")
        self.label_7.setObjectName("label_7")

#         self.label_5 = QtWidgets.QLabel(Dialog)
#         self.label_5.setGeometry(QtCore.QRect(100, 180, 421, 51))
#         self.label_5.setStyleSheet("font: 75 20pt \"Agency FB\";\n"
# "color: rgb(255, 0, 0);")
#         self.label_5.setObjectName("label_5")

        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(1200, 0, 800, 1400))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(1200, 55, 421, 51))
        self.label_8.setStyleSheet("font: 75 18pt \"Agency FB\";\n""color: rgb(0, 0, 0);\n""\n""")
        self.label_8.setObjectName("label_8")

        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(1200, 150, 800, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")


        #label 1
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 200, 421, 51))
        self.label.setStyleSheet("font: 75 18pt \"Agency FB\";")
        self.label.setObjectName("label")

        #label 2
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 660, 421, 51))
        self.label_3.setStyleSheet("font: 75 18pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")


       #label2 *
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(100, 650, 421, 51))
        self.label_9.setStyleSheet("font: 75 20pt \"Agency FB\";\n""color: rgb(255, 0, 0);")
        self.label_9.setObjectName("label_9")

        # browser 1 + lables
        self.label_a = QtWidgets.QLabel(Dialog)
        self.label_a.setGeometry(QtCore.QRect(130, 285, 160, 50))
        self.label_a.setStyleSheet("font: 75 15pt \"Agency FB\";\n")
        self.label_a.setObjectName("label_a")

        # browser 2 + lables
        self.label_b = QtWidgets.QLabel(Dialog)
        self.label_b.setGeometry(QtCore.QRect(130, 365, 160, 50))
        self.label_b.setStyleSheet("font: 75 15pt \"Agency FB\";\n")
        self.label_b.setObjectName("label_a")

        # browser 3 + lables
        self.label_c = QtWidgets.QLabel(Dialog)
        self.label_c.setGeometry(QtCore.QRect(130, 445, 160, 50))
        self.label_c.setStyleSheet("font: 75 15pt \"Agency FB\";\n")
        self.label_c.setObjectName("label_a")

        # browser 4 + lables
        self.label_d = QtWidgets.QLabel(Dialog)
        self.label_d.setGeometry(QtCore.QRect(130, 840, 160, 50))
        self.label_d.setStyleSheet("font: 75 15pt \"Agency FB\";\n")
        self.label_d.setObjectName("label_a")

        # browser 5 + lables
        self.label_e = QtWidgets.QLabel(Dialog)
        self.label_e.setGeometry(QtCore.QRect(130, 990, 160, 50))
        self.label_e.setStyleSheet("font: 75 15pt \"Agency FB\";\n")
        self.label_e.setObjectName("label_a")



        # browser 1_result + lables
        self.label_a_result = QtWidgets.QLabel(Dialog)
        self.label_a_result.setGeometry(QtCore.QRect(255, 285, 960, 50))
        self.label_a_result.setStyleSheet("font: 75 15pt ;\n""font-style:italic")
        self.label_a_result.setObjectName("label_a")


        # browser 2_result + lables
        self.label_b_result = QtWidgets.QLabel(Dialog)
        self.label_b_result.setGeometry(QtCore.QRect(250, 365, 960, 50))
        self.label_b_result.setStyleSheet("font: 75 15pt ;\n""font-style:italic")
        self.label_b_result.setObjectName("label_a")

        # browser 3_result + lables
        self.label_c_result = QtWidgets.QLabel(Dialog)
        self.label_c_result.setGeometry(QtCore.QRect(200, 445, 960, 200))
        self.label_c_result.setStyleSheet("font: 75 15pt ;\n""font-style:italic")
        self.label_c_result.setObjectName("label_a")

        # browser 4_result + lables
        self.label_d_result = QtWidgets.QLabel(Dialog)
        self.label_d_result.setGeometry(QtCore.QRect(235, 830, 960, 200))
        self.label_d_result.setStyleSheet("font: 75 12pt ;\n""font-style:italic")
        self.label_d_result.setObjectName("label_a")

        # browser 5_result + lables
        self.label_e_result = QtWidgets.QLabel(Dialog)
        self.label_e_result.setGeometry(QtCore.QRect(235, 990, 960, 300))
        self.label_e_result.setStyleSheet("font: 75 12pt ;\n""font-style:italic")
        self.label_e_result.setObjectName("label_a")




        #
        #browser 1
        self.textBrowser_4 = QtWidgets.QFrame(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(120, 275, 960, 350))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_4.setMidLineWidth(1)  # 设置中线宽度
        self.textBrowser_4.setFrameShadow(QFrame.Plain)  # 设置阴影效果：凸起
        self.textBrowser_4.setFrameShape(QFrame.Box)
        self.textBrowser_4.setLineWidth(1)

        #browser 2
        self.textBrowser_5 = QtWidgets.QFrame(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(120, 830, 960, 450))
        self.textBrowser_5.setObjectName("textBrowser_4")
        self.textBrowser_5.setMidLineWidth(1)  # 设置中线宽度
        self.textBrowser_5.setFrameShadow(QFrame.Plain)  # 设置阴影效果：凸起
        self.textBrowser_5.setFrameShape(QFrame.Box)
        self.textBrowser_5.setLineWidth(1)



        #
        # self.web_view = QWebEngineView(self.textBrowser_4)
        # self.web_view.load(QUrl(QFileInfo("D:/arcpy_project/Scripts/method/map_test.html").absoluteFilePath()))
        # map_html = """





        #
        # # Set the HTML content in the QTextBrowser
        # self.web_view.setHtml(map_html)
        # self.web_view.resize(920, 550)
        # self.web_view.move(0, 0)



        # layout = QVBoxLayout()
        # self.browser = QWebEngineView()  # 加载本地html
        # self.browser.load(QUrl(QFileInfo("D:/arcpy_project/Scripts/method/map_test.html").absoluteFilePath()))
        # # self.setCentralWidget(self.browser)
        # layout.addWidget(self.textBrowser_4)
        # layout.addWidget(self.browser)

        # Set the layout for the custom widget
        # self.setLayout(layout)
        # win1 = QWidget()
        # win1.setGeometry(500, 500, 400, 400)
        # win1.setStyleSheet("background-color:yellow;")
        # hbox = QHBoxLayout()
        # hbox.addWidget(win1)


        # self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        # self.pushButton_2.setGeometry(QtCore.QRect(1070, 420, 100, 40))
        # self.pushButton_2.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.pushButton_2.setObjectName("pushButton_2")

        # self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        # self.pushButton_5.setGeometry(QtCore.QRect(1070, 650, 100 ,40))
        # self.pushButton_5.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.pushButton_5.setObjectName("pushButton_5")

        # self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        # self.pushButton_6.setGeometry(QtCore.QRect(1070, 880, 100, 40))
        # self.pushButton_6.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.pushButton_6.setObjectName("pushButton_6")

        #label 3
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 750, 421, 51))
        self.label_4.setStyleSheet("font: 75 18pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")


        #file path label
        self.file_path_label = QtWidgets.QLabel(Dialog)
        self.file_path_label.setGeometry(QtCore.QRect(360, 660, 500, 52))
        self.file_path_label.setStyleSheet("font: 75 10pt ;")



        # self.label_10 = QtWidgets.QLabel(Dialog)
        # self.label_10.setGeometry(QtCore.QRect(120, 1100, 421, 51))
        # self.label_10.setStyleSheet("font: 75 18pt \"Agency FB\";")
        # self.label_10.setObjectName("label_10")

        # self.calendarWidget = QtWidgets.QDateTimeEdit(Dialog)
        # self.calendarWidget.setGeometry(QtCore.QRect(535, 980, 401, 65))
        # self.calendarWidget.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.calendarWidget.setObjectName("calendarWidget")

        #upload button
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(850, 670, 152, 52))
        self.pushButton_1.setStyleSheet("background-color: rgb(223, 223, 223);\n""font: 75 15pt \"Agency FB\";""color:rgb(12, 59, 46);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(self.upload_file)


        # model matching button
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(1030, 670, 152, 52))
        self.pushButton_2.setStyleSheet("background-color: rgb(109, 151, 115);\n""font: 75 15pt \"Agency FB\";""color:white")
        # self.pushButton_2.setStyleSheet("background-color: rgb(238, 238, 238);\n""font: bold 15pt \"Agency FB\";""color:rgb(12, 59, 46)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.match)




        #next button
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1030, 1300, 152, 52))
        self.pushButton_3.setStyleSheet("background-color: rgb(12, 59, 46);\n""font: 75 20pt \"Agency FB\";""color: white;")
        self.pushButton_3.setObjectName("pushButton_3")

        # previous button
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 1300, 152, 52))
        self.pushButton_4.setStyleSheet("background-color: rgb(12, 59, 46);\n""font: 75 20pt \"Agency FB\";""color: white;")
        self.pushButton_4.setObjectName("pushButton_4")



        # self.comboBox = QtWidgets.QComboBox(Dialog)
        # self.comboBox.setGeometry(QtCore.QRect(535, 200, 635, 65))
        # self.comboBox.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.comboBox.setObjectName("comboBox")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")

        # self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        # self.comboBox_2.setGeometry(QtCore.QRect(535, 1100, 401,65))
        # self.comboBox_2.setStyleSheet("font: 75 15pt \"Agency FB\";")
        # self.comboBox_2.setObjectName("comboBox_2")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # self.some_instance = ap.Ui_application_page()
        # self.some_instance.handle_top_left.connect(self.handle_top_left)

        button_object_names = ["pushButton_2", "pushButton_1", "pushButton_3","pushButton_4"]  # Add more button object names if needed

        for button_name in button_object_names:
            # Find the button by its object name
            button = getattr(self, button_name)
            if isinstance(button, QPushButton):
                # Set default cursor shape to arrow
                button.setCursor(Qt.ArrowCursor)

                # Connect signals to slots
                button.enterEvent = lambda event, button=button: self.changeCursorToHand(button)
                button.leaveEvent = lambda event, button=button: self.changeCursorToArrow(button)


    def changeCursorToHand(self, button):
        button.setCursor(Qt.PointingHandCursor)  # Change cursor to pointing hand when mouse enters button area


    def changeCursorToArrow(self, button):
        button.setCursor(Qt.ArrowCursor)

    def closeEvent(self, event):
        confirm = QMessageBox.question(
            self, "Confirm Close",
            "Are you sure you want to close the application?",
            QMessageBox.Yes | QMessageBox.No, QMessageBox.No
        )

        if confirm == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

    def match (self,Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label_d_result.setText(_translate("Dialog", "Slope, Project_Raster, Raster_Calculator,\n Focal_Statistics, Reclassify, Distance_Accumulation,\n Raster_Domain, Raster_To_Polyline, Mosaic, \nExtract_By_Mask, Stream_link, Watershed "))

        self.label_e_result.setText(_translate("Dialog", "Step 1: Slope -> Project_Raster -> Raster_Calculator ->\n Focal_Statistics -> Reclassify\n Step 2: Slope -> Raster_Calculator -> Raster_To_Polyline\n -> Distance_Accumulation ->Raster_Calculator \n-> Raster_Calculator\n -> Mosaic -> Extract_By_Mask\nStep 3: Raster_Calculator -> Stream_link -> Watershed ->\n Project_Raster -> Raster_To_Polygon -> Raster_Domain "))

    def upload_file(self):
        _translate = QtCore.QCoreApplication.translate
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(self, "Open File", "", "All Files (*);;Text Files (*.txt)", options=options)
        if file_path:
            dname = file_path
            if '\\' in dname:
                while (dname.count('\\') > 0):
                    mun = dname.find('\\')
                    dname = dname.replace(dname[0:mun + 1], '')
            elif '/' in dname:
                dname = dname.replace('//', '/')
                while (dname.count('/') > 0):
                    mun = dname.find('/')
                    dname = dname.replace(dname[0:mun + 1], '')


            # Split the file name into two lines
            lines = dname.split('/')
            formatted_name = "<br>".join(lines)
            self.file_path_label.setText(_translate("Dialog", formatted_name))
            # # Set the label's text with line breaks
            # self.file_label.setText(formatted_name)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Automatic Geomorphological Classification Tool", "Automatic Geomorphological Classification Tool"))


        self.label_a.setText(_translate("Dialog", "Application:"))
        self.label_b.setText(_translate("Dialog", "Resolution:"))
        self.label_c.setText(_translate("Dialog", "Region:"))
        self.label_d.setText(_translate("Dialog", "Models:"))
        self.label_e.setText(_translate("Dialog", "Workflow:"))

        # self.label_a_result.setText(f"{self.top_left_value}, {self.bottom_right_value}")

        # self.some_instance = ap.Ui_application_page()
        # self.some_instance.handle_top_left.connect(self.handle_top_left)

        # self.label_b_result.setText(_translate("Dialog", "30 m"))

        # self.label_c_result.setText(_translate("Dialog", "" ))

        # self.label_c_result.setText(_translate("Dialog", "POLYGON((113.44277777781963 31.666388888880796\n" "113.44277777781963 32.693055555547467\n""113.4805555555974 32.693055555547467\n" "113.4805555555974 31.666388888880796))\n" ))


        self.label_d_result.setText(_translate("Dialog", ""))


        self.label_e_result.setText(_translate("Dialog", ""))


        self.label_2.setText(_translate("Dialog", "Application Setting"))
        self.label_6.setText(_translate("Dialog", "Model Selecting"))
        self.label_7.setText(_translate("Dialog", "Data Matching"))
        # self.label_5.setText(_translate("Dialog", "*"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Agency FB\',\'serif\'; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Agency FB\',\'serif\'; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:80px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Agency FB\',\'serif\'; font-size:20pt; font-weight:600;\">Model Knowledge Graph</span> </p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Agency FB\',\'serif\'; font-size:15pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Agency FB\',\'serif\'; font-size:15pt;\">Once the application is selected by the user, the corresponding models are automatically linked as a workflow based on the user's requirements. The model ontology in geo-computation ontology is designed as below. </span> </p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:20px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:-160px;\">          <img src=\":/pic/model.png\" width=\"745\" height=\"650\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Agency FB\',\'serif\'; font-size:15pt;\">The requirements of input data are specified in the model ontology, which can be used as constraints to select datasets. Once the dataset is selected, the models will be parameterized according to the features of the dataset.</span> </p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "Description"))
        self.label.setText(_translate("Dialog", "Application Input:"))
        self.label_3.setText(_translate("Dialog", "Knowledge Graph:"))
        self.label_9.setText(_translate("Dialog", "*"))
        # self.pushButton_2.setText(_translate("Dialog", "Start"))
        # self.pushButton_5.setText(_translate("Dialog", "Clear"))
        # self.pushButton_6.setText(_translate("Dialog", "Save"))
        self.label_4.setText(_translate("Dialog", "Matching Result:"))
        # self.label_10.setText(_translate("Dialog", "Please Select Resolution:"))

        self.pushButton_1.setText(_translate("Dialog", "Upload"))
        self.pushButton_2.setText(_translate("Dialog", "Model Query"))
        self.pushButton_3.setText(_translate("Dialog", "Next"))
        self.pushButton_4.setText(_translate("Dialog", "Previous"))



    # def update_label_with_coordinates(self, top_left, bottom_right):
    #     _translate = QtCore.QCoreApplication.translate
    #     text = f"Coordinates: Top Left - {top_left}, Bottom Right - {bottom_right}"
    #     self.label_a_result.setText(_translate("Dialog",text ))
    def update_label_with_coordinates(self, top_left, bottom_right):
        text = f"  Top Left:\n {top_left}\n Bottom Right:\n {bottom_right}"
        self.label_c_result.setText(text)

    # def update_label_with_coordinates(self, top_left, bottom_right, decimal_places=2):
    #     # Format the coordinates with limited decimal places
    #     top_left_formatted = f"({top_left[0]:.{decimal_places}f}, {top_left[1]:.{decimal_places}f})"
    #     bottom_right_formatted = f"({bottom_right[0]:.{decimal_places}f}, {bottom_right[1]:.{decimal_places}f})"
    #
    #     # Construct the text to display
    #     text = f"Top Left: {top_left_formatted}\nBottom Right: {bottom_right_formatted}"

        # Set the text of the label
        # self.label_c_result.setText(text)



    def update_label_with_task(self,  value):
        text = f"  {value}"
        self.label_a_result.setText(text)
    def update_label_with_resolution(self,  value):
        text = f"  {value}"
        self.label_b_result.setText(text)

import model_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_model_page()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
